-- Table: engangsbeløp

-- DROP TABLE engangsbeløp;

CREATE TABLE IF NOT EXISTS engangsbeløp
(
    engangsbeløpsid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    type varchar(50) NOT NULL,
    sak varchar(20) NOT NULL,
    skyldner varchar(20) NOT NULL,
    kravhaver varchar(20) NOT NULL,
    mottaker varchar(20) NOT NULL,
    vedtaksid integer NOT NULL,
    gyldig_fra timestamp DEFAULT now() NOT NULL,
    gyldig_til timestamp,
    gjort_ugyldig_av_vedtaksid integer,
    beløp float,
    betalt_beløp float,
    valutakode varchar(10),
    resultatkode varchar(255) NOT NULL,
    innkreving varchar(20) NOT NULL,
    referanse varchar(50),
    opprettet_av varchar(50) NOT NULL,
    opprettet_tidspunkt timestamp DEFAULT now() NOT NULL,
    endret_av varchar(50),
    endret_tidspunkt timestamp,
    CONSTRAINT engangsbeløp_pkey PRIMARY KEY (engangsbeløpsid)
    )

    TABLESPACE pg_default;

CREATE INDEX idx_engangsbeløp_1 ON engangsbeløp(sak);